### ISSUE TITLE
MVT: Clarify the georeferencing in the conformance class

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-tiles#103]
Mapbox Vector Tiles encodes geometry as quantized coordinates to a finer resolution than the target device resolution of vector tiles (often a 4096 x 4096 grid targeting 256 x 256 0.28 mm pixels).
However it specifies nothing about the geospatial referencing of the data, so the [conformance class](http://docs.ogc.org/DRAFTS/20-057.html#rc_mvt) should cover this.

Many implementations use WebMercatorQuad (EPSG:3857), where the quantized grid is mapped linearly to the extent in projected EPSG:3857 coordinates.

Our implementation supporting MVT output for other TileMatrixSets does the same for other TMS / CRSes.
e.g. WorldCRS84Quad linearly maps geographic latitude, longitude to the grid.
WorldMercatorWGS84Quad (EPSG:3395) would linearly map the grid to the projected tile's extent in World Mercator coordinates (example tile: https://maps.ecere.com/ogcapi/collections/Daraa:AgricultureSrf/tiles/WorldMercatorWGS84Quad/12/1656/2460.mvt).

We should probably specify this clearly in the conformance class, as I don't believe this is covered by the MVT specification.

We should also allow a `crs` query parameter to override this (as discussed in #75 in the context of GeoJSON enforcing CR84, e.g. `crs=EPSG:4326` would force to linearly map the quantization grid to latitude, longitude for the tile's extent rather than projected coordinates). This `crs` capability would be a separate conformance class or extension, and may only be supported for a CRS whose axes align with the TileMatrixSet's in the case of MVT where a square quantization grid is use, otherwise the distorted re-projection of the tile makes things overly complicated. (Note that it is not so useful in the case of MVT, as it is to for GeoJSON to establish a "prior arrangement" that we really want to use the TileMatrixSet's projected CRS instead of CRS84, therefore few servers may decide to implement `crs=` for MVT).

NOTE: We should also rename the conformance class from "Mapbox" to MVT or "Mapbox Vector Tiles"

@jeffharrison

**Comment by joanma747** [comment]
A sub-requirement C was added both for GeoJSON and Mapbox to discuss the possibility of a CRS different from the TMS.
