### ISSUE TITLE
Create an OpenAPI requirements class

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-tiles#104]
inspired in http://docs.ogc.org/DRAFTS/18-062.html#requirements-class-openapi_3_0-clause

and the one in OGC API common

and add what #101 proposes.

**Comment by joanma747** [comment]
See the new conformance class. It is very simple because the OGC API common (a dependency) provides already many details.

**Comment by jerstlouis** [comment]
SWG 2021-12-23: We discussed re-purposing this OpenAPI conformance class as a requirement specifying operation ID suffixes to be used for path descriptions.

The table attached lists these and will be referenced by the requirement.
[TilesOperationIds.ods](https://github.com/opengeospatial/ogcapi-tiles/files/7770653/TilesOperationIds.ods)

@joanma747

**Comment by joanma747** [comment]
Table of operationId suffixes added as a new requirement in the standard candidate

**Comment by joanma747** [comment]
Accepted in the regular telco
