### ISSUE TITLE
Semantics on tile description object is unclear

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/ogcapi-tiles#11]
As discussed in https://github.com/opengeospatial/OGC-API-Tiles/issues/3#issuecomment-585809931 the semantics of `item` links from the Tile Description object are unclear.

The object at `/tiles` should likely be called something like Tile Set, as it _is_ the resource, it is not a description of the resource. 

From here we likely need to clarify what the appropriate link type to the potential tiles is.

**Comment by joanma747** [comment]
replase to tileset resource.

**Comment by joanma747** [comment]
On June 02, 2020 we decided that "Tile description" returned in \tiles   will be named "Tile Sets" in plural and  \tiles\MyTileMatrixSet will be called "Tile Set".

**Comment by ghobona** [comment]
Review this issue after Issue https://github.com/opengeospatial/OGC-API-Tiles/issues/43 is resolved.

**Comment by joanma747** [comment]
There is a mistake to correct in the links rel types. See

![image](https://user-images.githubusercontent.com/5230444/98267268-79d74b80-1f8b-11eb-83a0-1fd1b1e3be5b.png)

**Comment by joanma747** [comment]
#43 is closed. Can we close this one?.

**Comment by joanma747** [comment]
>The object at /tiles should likely be called something like Tile Set, as it is the resource, it is not a description of the resource.

Correct the in Table 1 of resource names and common paths. User the "TileSet" expression there are suggested.

**Comment by jerstlouis** [comment]
That particular resource should say "List of TileSets", and if we specifically discuss that full path in an OGC API, that should probably be "List of multi-layer vector TileSets" (with considerations related to the use of the "vector tile" term).

**Comment by jerstlouis** [comment]
SWG 2021-08-12: As also identified in #8, the spec is still quite unclear in how it uses in many places "tiles description".
Instead, suggesting that "tileset metadata resource" and "tilesets resource" be used consistently throughout.

**Comment by jerstlouis** [comment]
Abstract tests 2, 3, 4, 5, 14 still use "tiles description".

**Comment by joanma747** [comment]
"Tile description" and related expressions removed.
