### ISSUE TITLE
IETF work on Link templates

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-tiles#114]
There is progress in IETF towards an RFC for a `Link-Template` header in addition to the `Link` header (RFC 8288) that we use as the basis for links in OGC API standards. See https://github.com/opengeospatial/ogcapi-common/issues/288.

Since templated links are essential in Tiles, we should consider the proposal and if there are any issues with respect to the current implementation. In general, I think that we can keep the current approach, maybe with the following clarifications:

* Link templates should not be encoded in a Link header, but should be encoded in a Link-Template header.
* In addition to the `templated` member, consider adding also an optional `var-base` (or `varBase` or `varbase`) member with the same meaning as in the Internet-Draft.

Template parameters like `tileRow` are API building blocks that should have a persistent OGC URI so that users can determine the description of the parameters, if the base URI is declared in the var-base.

**Comment by jerstlouis** [comment]
@cportele 

Thanks for pointing this out.

I don't think there is any requirement in the specification about returning links in the response headers, but we are probably inheriting the recommendation to include links from the payload in the response headers as well from _Common_ and _Features_.

If I understand the _var-base_ correctly, it seems like it could perhaps sometimes be used with some of the ideas for dynamic enumerations proposed in https://github.com/opengeospatial/ogcapi-common/issues/302, where one could find a JSON Schema enumerating potential values (e.g., the list of valid tileMatrixSetId). However where the values of those variable depends on other variables though (as discussed e.g. in https://github.com/json-schema-org/json-schema-vocabularies/issues/36), such as on the collection / tileMatrixSet, and even the rows and columns depending on the tile matrix, it would possibly require the var-base to itself be templated, which might not have been considered by the spec. There could at least be some non-machine interpretable explanations of the variables available though.

For the following link array element:
```json
{
  "rel" : "item",
  "type" : "image/png",
  "title" : "GNOSISGlobalGrid map tiles for blueMarble (as PNG)",
  "href" : "/ogcapi/collections/blueMarble/map/tiles/GNOSISGlobalGrid/{tileMatrix}/{tileRow}/{tileCol}.png",
  "varBase": "/ogcapi/vars",
  "templated" : true
},
```

I imagine the _Link-Template_ response for this would look like:

```
Link-Template: </ogcapi/collections/blueMarble/map/tiles/GNOSISGlobalGrid/{tileMatrix}/{tileRow}/{tileCol}.png>;
               rel="item";
               type="image/png";
               var-base="/ogcapi/vars"
```

@joanma747 is there anything we should add to the specification for this?
Perhaps a recommendation to include the Link-Templates, and adding varBase to the OpenAPI schemas?
