### ISSUE TITLE
Question about recommendation and permission identifiers

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/ogcapi-tiles#129]
In Chapter 7. Requirement Class "Core", there are permissions and recommendations with `/per/tileset/*` and `/rec/tileset/*` identifiers.  For example, `/per/tileset/tc-core-tile-encoding`, `/rec/tileset/tc-success-scale`, `/rec/tileset/tc-deepfullempty`, and `/per/tileset/tc-core-html` are all included in the chapter on the core conformance class.  Then Chapter 8 goes on to discuss the tileset conformance class.

I understand this probably doesn't have any impact on what is actually specified, but I'm curious if the `/rec/<class>/<id>` type identifiers are at all significant.  Should the core conformance class only have things like `/per/core/*` and `/rec/core/*`?

The same thing happens later in the spec (`/per/tilesets/tilesets-api` appears in the tileset lists conformance class instead of the tileset conformance class).  Maybe there is no significance to the names.

I'm happy to help rename files if only `core` things should be in core etc.

**Comment by jerstlouis** [comment]
@tschaub Historically, the _tileset_ conformance class was the _core_ conformance class, and then we decided to separate out an even more minimalistic core that most existing tile services would already be conforming to -- that is where this is coming from.

I believe the identifiers do have some significance as they would be reported in conformance tests etc., so it would be good to have them consistent with the conformance classes that they are defined in, therefore a PR would be welcomed. Thank you!

**Comment by joanma747** [comment]
Fixed in several files
