### ISSUE TITLE
Metanorma issue? Normative References section says there are no normative references

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-tiles#135]
See https://opengeospatial.github.io/ogcna-auto-review/20-057.html#toc13

> _There are no normative references in this document._

https://github.com/opengeospatial/ogcapi-tiles/blob/master/core/standard/clause_3_references.adoc does not contain that text.

Is this an issue with metanorma? It also appears in the PDF.

@ghobona

**Comment by ghobona** [comment]
Issue fixed in final release.

![Screenshot 2022-12-08 at 11 13 24](https://user-images.githubusercontent.com/18121038/206432794-b30f21fa-f881-4347-bcee-e8bfd19a7d14.png)
