### ISSUE TITLE
Updating of the Implementations page

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-tiles#137]
@joanma747 @jerstlouis @cportele @jj0hns0n @aaime @notthatbreezy @francbartoli @Lestark728 @robinhoutmeyers @tschaub

Please update details of your products on the [Implementations](https://github.com/opengeospatial/ogcapi-tiles/blob/master/implementations.adoc) page by 2022-11-28, as participants of the Web Mapping Code Sprint are likely to explore the implementations.

Please also check that the URL referencing your product does not return an error.

**Comment by tschaub** [comment]
My updates here: #138
