### ISSUE TITLE
Broken links for HTML and PDF versions of the standard

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/ogcapi-tiles#151]
The links on [this](https://github.com/doublebyte1/ogcapi-tiles#ogc-api---tiles) section point to:
https://opengeospatial.github.io/ogcna-auto-review/20-057.html
https://opengeospatial.github.io/ogcna-auto-review/20-057.pdf

Both throw a 404 error

**Comment by jerstlouis** [comment]
Closing because PR # 143 addressing this issue is merged.
