### ISSUE TITLE
"link" element on the TileSetMetadata data structure

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/ogcapi-tiles#165]
On table 13 of the standard, the TileSetMetadata data structure has an element called "link"(singular), which contains links to related resources.

https://docs.ogc.org/is/17-083r4/17-083r4.html#toc22

Is it really "link" or "links", like in these implementations?
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map/tiles/WorldCRS84Quad?f=json
https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_mosaic_2019/tiles?f=json
https://api.pdok.nl/lv/bag/ogc/v1_0/tiles/NetherlandsRDNewQuad?f=json

**Comment by jerstlouis** [comment]
@doublebyte1 See the [note in section 7.1](https://docs.ogc.org/is/17-083r4/17-083r4.html#toc18) about how the logical model is mapped to actual property names in the JSON encoding:

> In addition, **all elements with multiplicity greater than one have names changed to plural**. Please be aware of irregular plurals such as tileMatrix that changes to tileMatrices.

You can also see the actual property names including the plural `links` in the JSON Schema for TileSet metadata:

https://schemas.opengis.net/tms/2.0/json/tileSet.json
