### ISSUE TITLE
Tiles from multiple collections should not default to all collections, and should have limits

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ogcapi-tiles#17]
The current default, returning multi-layer tiles with all the collections available, is a dangerous default that assumes there will be few collections... which is often not the case.

Point in case, many GeoServer services around have thousands of layers/collections, the day they upgrade to a version of GeoServer supporting the Tiles API, this endpoint will cause inadverted "denial of service" attack with people just playing with the API.

Generally speaking, the API should not be designed with a "small number of collections" in mind.
Suggestions:

- Allow a server to demand the list of layers to be provided (no automatic default, if the server wants to provide it, then it's another store)
- Allow a server to impose and advertise a maximum number of collections that can be requested on this resource.

There is a parallel with WMS, where the number of layers in a request is limited only by the maximum length of a URL. In GeoServer this has been handled by adding a time limit on GetMap requests, which will truncate execution of requests that are too long (typical defaults, 60 seconds, but seen many servers limiting it to just 10). It works in terms of keeping the server up, but clients cannot discover the limit nor can figure out that the request failed because of it.

**Comment by joanma747** [comment]
The proposed solution in #18 solves also this issue. So the proposed solution is:

- Allow a server to impose and advertise the allowed combinations of collections instead of allowing for any possible combination.

**Comment by ghobona** [comment]
If the proposed solution solves the issue and the proposed solution has been closed, then perhaps this issue can be closed?

**Comment by mcechini** [comment]
IMO, we are losing functionality currently available through WMS if we go with this suggestion:

> Allow a server to impose and advertise the allowed combinations of collections instead of allowing for any possible combination.

We currently have roughly 1000 visualization products.  Supporting a /map request on each one individually is, of course, possible.  Supporting a /map request on all collections is untenable... but so also is advertising combinations.

**Comment by joanma747** [comment]
To close this we need to verify that the request to dataset tiles allows the server to pick ad choose the right amount of info when collection ids are not specified as query parameters.

**Comment by jerstlouis** [comment]
_10. Requirement Class "Dataset Tile Sets"_ says:

> If an API offers several geospatial data resources for a dataset, it may limit the number of collections that can be retrieved together, and/or provide a limited subset of the collections by default.

So I believe this is covered?

**Comment by jerstlouis** [comment]
SWG 2021-08-12: Agreed that this is covered. It was also noted that the list of collections included may be included in the the tileset metadata at `/tiles/{tileMatrixSetId}`. However we also realized that Requirement 15 is not clear as to which resource the `collections` query parameter applies. In the OpenAPI definition currently `collections` is only defined for the individual tiles, however it would also be useful for the tileset so that the list of layers could be returned accordingly. A separate issue will be filed about this.
