### ISSUE TITLE
extents (spatial and optionally temporal) on the Tiles Description response

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/ogcapi-tiles#22]
The biggest advantage of WMTS over XYZ today is that with a WMTS response you get the bounds, and the client can zoom to the area where the tiles cover.

Would be good to add the extent object (just use the same structure at the collection level), so that providers can specify the bounds. I'd consider making it required, even though it duplicates a bit of info with the collection, as it'll be nice for clients to not have to follow a link to get the bounds.

I'd say spatial should be required, with temporal optional. Might also be nice to have the recommended / relevant zoom levels, but that can be a separate issue.

**Comment by cholmes** [comment]
I can make a PR for this if there is interest in it.

**Comment by jerstlouis** [comment]
The extent is in /collections/{collectionID}, but I can definitely see this as important if the /tiles can be used stand-alone.

**Comment by cholmes** [comment]
Yeah, this definitely came up when thinking about the standalone use case. Same with #12 - it's at the collection, but useful to have at /tiles/ for standalone.

**Comment by ghobona** [comment]
@cholmes Does your offer (https://github.com/opengeospatial/OGC-API-Tiles/issues/22#issuecomment-617244004) to prepare a PR  still stand?

**Comment by joanma747** [comment]
New recommedation tileset/bbox added.
