### ISSUE TITLE
Prepare draft Charter

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-tiles#34]
A draft charter for formally establishing a SWG to work on OGC API - Tiles is at https://github.com/opengeospatial/OGC-API-Tiles/blob/master/charter/OGC-API-Tiles-SWG-Charter.adoc

OGC members are welcome to become Charter Members of the SWG.

**Comment by jeffharrison** [comment]
Gobe,

Thanks! I would be pleased to be a Charter Member...  Jeff Harrison, US Army Geospatial Center 

Thanks and Regards,
Jeff

**Comment by joanma747** [comment]
Does this mean that we are splitting the group into two charters; one for tiles and the other for maps?

**Comment by ghobona** [comment]
SWG decision on 2020-05-28

The following should be added to the Charter.

The OGC API - Tiles SWG will meet with the OGC API - Maps SWG on a regular basis.

**Comment by ghobona** [comment]
Statement about regular engagement between the Maps and Tiles SWGs has been [added](https://github.com/opengeospatial/OGC-API-Tiles/commit/729cd8ae8bb9540b28e70aaca4cbcd1368c05492).

**Comment by ghobona** [comment]
On 2020-06-04 the SWG passed the following [motions](https://portal.ogc.org/files/?artifact_id=93454):

* The WMS SWG approves the re-chartering of the WMS SWG as the OGC API – Maps SWG.
* The WMS SWG recommends to the OGC Technical Committee the creation of the OGC API – Tiles SWG, subject to the creation of a charter for the new SWG.

**Comment by ghobona** [comment]
2020-07-09 SWG telecon: There was no objection to asking the TC Chair to start the TC vote as soon as the Architecture DWG endorsement vote ends on 2020-07-10.

**Comment by ghobona** [comment]
2020-07-13. Three-week TC review ends on 2020-08-03.

**Comment by joanma747** [comment]
Thanks for facilitating this.
