### ISSUE TITLE
error conditions for geodata parameter

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ogcapi-tiles#46]
> 10.4.3. Error conditions
>
> "If the value of the parameter geodata contains a resource id of URI that does not exist on the API, the status code of the response is 404."

I'm not sure I like this.  An invalid query-parameter value is typically handled by throwing a more-generic 400 response.  I think it's better to reserve 404 responses for incorrect paths.  (Either way, of course, we really do need a standard exception report indicating what the actual issue is.)

> "If the value of the parameter geodata has a wrong format or combines one of more geospatial data resources that are not compatible (e.g. they do not have a compatible value specified by other parameters in the request), the status code of the response is 500."

This is definitely wrong.  This is a bad request, and so should definitely be a 400 response.

**Comment by cportele** [comment]
+1, an invalid query parameter value requires a 400 response

**Comment by chris-little** [comment]
+1 to '400', having just editted all the `403`s to `400` in EDR API!

**Comment by joanma747** [comment]
linked to @21 that was already "resolved". Can we agree on this one too?

**Comment by jerstlouis** [comment]
This is now in 11.4.3 and "response is 500" is still wrong, it should say 400.

The 11.4 header "Dataset selection" is also confusing, as usually the dataset is the API as a whole.
Should it say "Selection of collections"

**Comment by jerstlouis** [comment]
Fixed by 2fab9d65351da1fb958c39c17831179febec23ff and 331792821691e0feda8c39942d6f7e5e023e6b3e.
