### ISSUE TITLE
Clarify how OGC API-Tiles supports feature data

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-tiles#50]
The OGC Vector Tiles Pilot (VTP) [demonstrated](http://docs.ogc.org/per/19-088r2.html#_interactive_instruments_d101_features_tiles_and_styles_api) how tiled feature data could be published through an implementation of both OGC API - Tiles and OGC API - Features.

Clarify how the recommendations and lessons learnt from VTP have been applied.

Please coordinate with the OGC API - Features SWG.

**Comment by ghobona** [comment]
**2020-12-10 Cross SWG discussion**

* Following the lessons from VTP we are able to serve vector tiles.
* Tile Set Metadata has been improved as a result of the VTP.
* Previously the draft standard focused on Tile Matrix Set Link. Now the focus is on Tile Set Metadata. It is a richer metadata element and is more useful.
* VTP worked on Filter and that is now being applied in the draft standards (i.e. Tiles API, Features API, Records API etc).
* Schemas might remain an item for further discussion. JSON Schema could potentially be used. 
* Can one embed JSON Schema inside a JSON document? OpenAPI does that.
* Styles API SWG came up with a queryable profile. 
* The Tiles API SWG will use a concrete instance of JSON Schema.
* Resolution: Whenever OGC API SWGs have a requirement to represent schemas, they should use JSON Schema.
* Action: The OGC API - Tiles SWG will try to implement geometry and properties descriptions as Geo-JSON schema
 using the approach described at https://github.com/opengeospatial/ogcapi-features/issues/424#issuecomment-720264251
* The DGGS SWG should engage on this topic too.
* To what extent the DGGS relates to the Abstract Tiling Spec and the 2D TMS? This needs to be considered.

**Comment by jerstlouis** [comment]
> Schemas might remain an item for further discussion. JSON Schema could potentially be used.
The Tiles API SWG will use a concrete instance of JSON Schema.

Specifically, the 2DTMS &TSMD standard's TileSet Metadata now uses JSON Schema to describe the schema of the feature properties found inside the tiles.

> To what extent the DGGS relates to the Abstract Tiling Spec and the 2D TMS? This needs to be considered.

Topic 21 DGGS - Part 4 - Axis-Aligned DGGS in particular, as a 2DTMS, especially variable width ones suitable for any area of the globe, should qualify as such.
