### ISSUE TITLE
Clarify how OGC API-Tiles supports maps

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-tiles#51]
Clarify how OGC API - Tiles works with OGC API - Maps to deliver map tiles.

This was demonstrated by both the UAB and CubeWerx demonstrations during the July 2020 OGC API - Maps Sprint. So all that is need is a brief summary and references to the relevant sections in the draft specs.

**Comment by ghobona** [comment]
This was demonstrated at several OGC Code Sprints in 2021 (February, May code sprints)

**Comment by jerstlouis** [comment]
Map Tiles are handled by OGC API - Maps.
Currently, this is in the [Map Tilesets conformance class](https://github.com/opengeospatial/ogcapi-maps/blob/master/extensions/partitioning/standard/clause_9_map_tilesets.adoc) of the "partitioning extension" (part 2?).
Potentially this could be a conformance class of Part 1... To be discussed in Maps.
