### ISSUE TITLE
Clarify whether OGC API-Tiles supports coverages

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-tiles#52]
It has been stated in the past that OGC API - Tiles supports coverages. To date, there have not been that many demonstrations of that capability.

So there is a need to clarify whether OGC API-Tiles supports coverages.

If there have not been any demonstrations of the capability, then OGC API - Tiles should be edited to remove the statements about coverages.

This would still allow a future extension of OGC API - Tiles to support coverages. However, for Part 1 the statements may need to be removed.

Please coordinate with the Coverages SWG on this topic.

**Comment by jerstlouis** [comment]
@ghobona OGC API - Tiles supports coverages, and should do so right away with the Core.

Example: https://maps.ecere.com/ogcapi/collections/SRTM_ViewFinderPanorama/tiles
e.g. https://maps.ecere.com/ogcapi/collections/SRTM_ViewFinderPanorama/tiles/GNOSISGlobalGrid/0/0/2.png
(v.s. map tile https://maps.ecere.com/ogcapi/collections/SRTM_ViewFinderPanorama/map/tiles/GNOSISGlobalGrid/0/0/2.png)

The coverage tile is raw data values encoded in 16-bit PNG with meters * 2.98 + 16384 (with 0 representing NODATA).
This linear mapping would not be necessary with e.g. 32-bit floating point GeoTIFF tiles which we'll implement at the code sprint next week.

As discussed in Coverages, it would be nice if there was a way to express both the range of values that one might find (e.g. -11034..8848 meters), and how these could be mapped to something like 16-bit integer as in this PNG example.

**Comment by ghobona** [comment]
**2020-12-10 Cross SWG discussion**

Ecere and CubeWerx have implementations of OGC API - Tiles that support tiled coverages.

**Comment by chris-little** [comment]
This is slightly aside, but I will be exploring the ability of CoverageJSON (not a standard, yet) to [support tiles](https://covjson.org/spec/#tiledndarray-objects).

**Comment by jerstlouis** [comment]
_Coverages_ now has a `coverage-tile` conformance class:

https://docs.opengeospatial.org/DRAFTS/19-087.html#_requirements_class_coverage_tiles
