### ISSUE TITLE
Remove reference or add context to "vector tiles" in Overview

### ISSUE THREAD

**Issue by mcechini** [opengeospatial/ogcapi-tiles#54]
The [Overview (Clause 6)](https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/clause_6_overview.adoc) provides a number of example APIs paths that are labeled as "vector tile".  

A preceding paragraph says:

> With time, the concept of a tile, initially used for map tiles has been generalized to other data models such as feature data (some vendors use the expression vector tiles) and even to coverage data or processes that can be parallelized dividing the space in tiles. This standard presents an approach to tiles that can be applied to almost every resource type that returns geospatial data. If applied in conjunction with the OGC API - Features standard and on top of a feature collection, the expected result is tiled feature data. If applied in conjunction with the OGC API - Maps standard and on top of a collection that is transformed into a map by applying a style, the result should be map tiles (usually in PNG or JPEG format).

So, while it is correct that the example paths could return vector tiles, it's not required.  Therefore the resource name should be generalized.  I think resolution to issue #43 may remove a couple of these items, but there will be some that remain.

**Comment by jeffharrison** [comment]
I would say use of the term vector tiles is the least of the questions that the referenced clause raises. For example, I don't quite understand why one needs the Features API or the Maps API to get Tiles...

Best Regards,
Jeff

**Comment by mcechini** [comment]
Yeah, I was trying to keep it simple. :) Just a basic "remove "vector tiles" from the resource names.  That felt doable without a big conversation.  Then we can always come back and revisit that paragraph separately.

**Comment by jeffharrison** [comment]
@mcechini Got it. To be honest with you, I don't really have an issue with the term vector tiles in the resource names. That said, I think the SWG should always consider edits that simplify things. What would you suggest as a replacement?

Thanks and Regards,
Jeff

**Comment by mcechini** [comment]
Ay, there's the rub.  When `/tiles` is within the context of `/map` (or maybe even `/feature`), you could say "map tiles" or "feature tiles" ...  If the spec is to support a root `/tiles` path, then I think those "Vector [Tt]iles?" resource names in Table 1 could simple just be "[Tt]iles?", dropping "Vector".  And perhaps a footnote on the "Tiles" header stating something to the affect of "Per requirement 7.4.7, tile response format may vary".

**Comment by mcechini** [comment]
Though perhaps this issue is now consumed by issue #56 that you just wrote

**Comment by joanma747** [comment]
I have followed the recommendation of the title of this issue. The expression __vector tiles__ is used as a footnote.
The section was reviewed several times after this issue was filed so I hoep the overview is better now. Howevers, if someone want to come up with a better overview, I'm open to consider pull requests.
