### ISSUE TITLE
Typos in /clause_6_overview.adoc

### ISSUE THREAD

**Issue by jeffharrison** [opengeospatial/ogcapi-tiles#56]
First, I'd like to congratulate and thank all the OGC members contributing to the Tiles API. Significant progress has been made on this important API. Second, we need to please take a moment to scrub the /clause_6_overview section. There seem to be a significant number of typos still (?)

I can help if needed (not exactly sure of the process). I did send a list of typos several months back. 

Thanks and Regards,
Jeff

**Comment by joanma747** [comment]
This is an old issue. Before closing it I read the overview again and made some corrections. WE can reopen de issue if more specific suggestions are provided.
