### ISSUE TITLE
Consider consolidation of TileJSON and "OGC JSON" Tileset definitions

### ISSUE THREAD

**Issue by mcechini** [opengeospatial/ogcapi-tiles#57]
Per discussion in issue #43, there is interest/concern in the duplication/overlap of content between the TileJSON and current OGC Tiles approach to defining a tileset.  This is a separate topic than what is specifically addressed in #43, so we can carve it out to it's own issue.

@cportele's initial statement:
>My point about merging both JSON documents is mainly about the fact that these are not really alternative formats, but clients may want to have information from both, because the content is complementary, so it seems better to merge the content into a single JSON document.

@jerstlouis's response:
> Well my impression from first learning about TileJSON in depth during the pilot and to some extent until now, is that the Tiles API OGC JSON is geared towards more native OGC services and its lineage can be traced back to WMTS, whereas the TileJSON really exists to accommodate the users of Mapbox tools.
> As I was pointing out, there was no overlap at all between the properties until we discussed adding the vector layers fields information to the OGC JSON. Even though they sort of express the same things, they did so in different ways, characteristic of the communities they're coming from, like zoom levels vs. tile matrix etc., so I would argue that mostly they are more alternative ways of expressing the tileset than complementary...
> But that's distinction might be a bit fuzzy, and of course the more we make the OGC JSON look like the TileJSON, the less this is true.

**Comment by joanma747** [comment]
My initial reaction is that the only specification that makes sense to compare is v3. https://github.com/mapbox/tilejson-spec/blob/3.0/3.0.0/example/osm.json (the only one that describes the  vector layers fields) unfortunately this version has been sitting in an independent (draft?) branch for 2 years now. 

Do we really have to force WMTS into a TileJSON that is still a draft and might not become adopted by nobody?
Still I see not support for other tileset that the ones in webmercatorquad

**Comment by cportele** [comment]
I think in order to make progress it is best to withdraw my comment / proposal. I can handle this issue in our implementation without any provisions in the spec.

**Comment by mcechini** [comment]
I do think there is room to improve our OGC tileset response to include some of the useful information that is within the TileJSON spec.  For example min/max zoom level, identifier, vector_layer info, etc...  Do we have an issue for that?

**Comment by joanma747** [comment]
If that is ok with everybody, we can continue discussing the OGC TileSets data model in the original issue as the proposal from Jerome is there: https://github.com/opengeospatial/OGC-API-Tiles/issues/43
I propose to close this issue if we agree on abandoning the consolidation. That does not mean that we will close our eyes to the TileJSON format. On the contrary, in defining the OGC TileSets data model we will "import" all good ideas we can get.

**Comment by mcechini** [comment]
Personally, I think we should use #43 to make changes to the `tilesets` resource only.  I don't believe the resolution to #43 requires any content changes to the `tileset` resource.  Issue #47 does, but that is a fairly straightforward change.  What Jerome proposes [here](https://github.com/opengeospatial/OGC-API-Tiles/issues/43#issuecomment-682714556) is specific to tilesets and we could move forward with that.  So, that means we would carve out a new issue for changes to `tileset` where the conversation can be focused... and potentially built on top of an already agreed upon set of changes from #43 and #47 (also ideally a merged PR so that we're all looking at the same documentation base).

**Comment by jerstlouis** [comment]
@joanma747 I believe we can leave this issue open for further discussion and focus on resolving the others first, as I think it is largely parallel as @mcechini points out. 
@cportele could propose a combined JSON if that makese sense which could then either become part of the standard or kept implementation-specific.

**Comment by joanma747** [comment]
The proposal is that we will not try to merge the TileJSON with the OGC JSON approach, soon. It is all about Tileset metadata. We are not dismissing the use of TileJSON as an alternative format. We are also reading the good ideas in TileJSON. 

We declare the issue "dormant".

**Comment by jerstlouis** [comment]
I believe we can close this issue as we have decided on defining a better suited, well defined TileSetMetata as defined in the [2D TMS and Metadata standard](https://github.com/opengeospatial/2D-Tile-Matrix-Set).

Implementations can provide a TileJSON representation as an alternative representation of the tileset resource, but any discussion of what goes in there should be handled by the [specification itself](https://github.com/mapbox/tilejson-spec).

**Comment by jerstlouis** [comment]
May 2021 OGC API - Tiles Sprint: Agreed this issue can be closed.
