### ISSUE TITLE
Improve the documentation of conformance classes

### ISSUE THREAD

**Issue by mcechini** [opengeospatial/ogcapi-tiles#58]
I'm having a hard time tracking down the different definitions and expectations for all the proposed conformance classes (e.g. Tileset vs Geodata-TilesetsList vs Dataset-TilesetsList).  Having a list of the conformance classes, how they are defined, and what the translate into w.r.t. supported API paths would be great.  Ideally on the main page of the repo so that it's front and center and I don't have to dig through a long specification document to try to piece together the differences.

([Here's](https://github.com/opengeospatial/OGC-API-Tiles/tree/mcechini-readme-updates) a code branch to add the updates).

**Comment by joanma747** [comment]
Those are nice updates to the readme.md page. If there is no objection I'll adopt them.

**Comment by mcechini** [comment]
I think it would be helpful for someone with more domain knowledge to flush that list out a bit more.  Maybe it should be a table?  I was envisioning these potential columns/pieces of information

- Class Name (e.g. Dataset-TilesetsList)
- Description
- Conformance Class URI (e.g. `http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/geodata-tilesets`)
- Example path(s) (e.g. `collections/{collection_id}/tiles/...`
- Link to standard documentation (e.g. [clause_9_tile_datasetTileSets.adoc](core/standard/clause_9_tile_datasetTileSets.adoc)... or somewhere better)

**Comment by joanma747** [comment]
Sorry if this is confusing. This is a good suggestion but it is better to have this in the conformance page so tables to resources examples are included in the conformance page of the standard to clarify this. Other element are also included in the direction of your suggestion. I will close this issue. If more clarity is needed we can reopen it again.
