### ISSUE TITLE
README.md has broken links

### ISSUE THREAD

**Issue by jorgejesus** [opengeospatial/ogcapi-tiles#60]
The following link doesn't work: 

- [https://github.com/opengeospatial/T-15-D014-WMTS_draft_specification](https://github.com/opengeospatial/T-15-D014-WMTS_draft_specification)

Maybe is needs replacement to [https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/OAPI_Tiles.adoc](https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/OAPI_Tiles.adoc)

**Comment by joanma747** [comment]
The whole /core/standard/README.md was very old. I decided to remove most of the content and point to the /README.md for more information. To many README.md to maintain.
