### ISSUE TITLE
Indicating a tile is full or empty all the way down to max zoom levels

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-tiles#63]
In order to support large high resolution polygon datasets such as global land or ocean features (e.g. generated from OpenStreetMap `natural=coastline`), a recommendation could be made to include in the response header of a 204 or 200 response of an empty or totally full (either for vector polygons, or raster tiles of a solid/transparent color), **for which nothing (or exactly the same thing for 'full') will be returned at all more detailed zoom levels**, an indication that this is the case, something like: `OATiles-hint: empty` or `OATiles-hint: full`. These hints should not be returned if at a deeper zoom level some new features appear, which were too small or otherwise omitted at lower zoom levels.

A similar indication (especially for full tiles, where an omitted tiles would not be rendered) would also be useful in data stores, e.g. for storing GeoPackage tiles.

This would drastically reduce the number of useless requests and or storage requirements for such datasets.

Related to and originally suggested in https://github.com/opengeospatial/ogcapi-tiles/issues/21, and discussed 2020-12-09 (December Members Meeting) Tiles SWG teleconference that an optional HTTP header response would be a sensible way to achieve this.

**Comment by jerstlouis** [comment]
These hints are already included in current version as _Recommendation 3_, and feedback from the last Tiles sprint was that they were indeed very useful, and easy to implement.

**Comment by joanma747** [comment]
In a SWG meet we decided to close the issue. Concerns about having other standards doing "tile availability" in a different way was stated. The tile set limits and this empty-full capability are components of the "tile availability" issues. 

See recommentation /rec/tileset/tc-deepfullempty
