### ISSUE TITLE
Test 12 refers to requirement that does not exist

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-tiles#65]
https://github.com/opengeospatial/ogcapi-tiles/blob/master/core/standard/abstract_tests/root/TEST012.adoc refers to `/req/tiles/root/root-success` which doesn't appear to exist.

Possibly this should point to `/req/dataset-tilesets/landingpage`?

If so, the `/ats/root/root-success` identifier probably should change too.

**Comment by joanma747** [comment]
Sure. Tests will be synchronized at a latter state.

**Comment by joanma747** [comment]
The ATS has been completely recreated from the new requirements so this problem has been OBE.
