### ISSUE TITLE
Updated list of implementations

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/ogcapi-tiles#74]
The [implementations doc](https://github.com/opengeospatial/ogcapi-tiles/blob/master/implementations.adoc) is a nice place  for people developing clients to look for services and vice-versa.  It looks like a number of those implementations have not kept up with changes in the spec (understandable).  I'm wondering if there are implementations that are staying up to date.  If so, are there any publicly accessible map tile servers?

**Comment by jerstlouis** [comment]
@tschaub I believe our "TileSet" schema (e.g. http://maps.ecere.com/ogcapi/collections/blueMarble/tiles/WebMercatorQuad?f=json) is still mostly up to date but missing some properties. We have recently added support for the new properties and will be deploying an update soon.

We need to review our TileMatrixSets (e.g. https://maps.ecere.com/ogcapi/tileMatrixSets/WebMercatorquad?f=json) to see what needs to be updated.

We are definitely planning to have everything up to date in time for (or early on during) the upcoming May 26-28 Maps/Tiles/Styles code sprint. Thanks!

**Comment by tschaub** [comment]
Thanks, @jerstlouis.  I'll keep an eye out for your updates.  I also just registered for [the sprint](https://www.ogc.org/ogcevents/may-2021-ogc-api-virtual-code-sprint), and help update a list of implementations after that.

**Comment by jerstlouis** [comment]
@tschaub We have just updated our test server with the new _TileMatrixSet_ and _Tileset Metadata_ definitions.
Please let myself, @slothtrop or @bonderado know if anything seems out of date! Thank you!

**Comment by jerstlouis** [comment]
The list of implementations was updated recently.
Some implementations should still be updated or removed after contacting the maintainers.
