### ISSUE TITLE
Responses respecting the original CRS.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-tiles#75]
See a commnet previous to the final resolution on how flexible the API should be in respecting the requested CRS.

https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/9

**Comment by jerstlouis** [comment]
THere are multiple aspects to this issue:
- Whether for a particular a format (e.g. GeoJSON) the response can be in a different CRS than the TileMatrixSet -- That should be allowed in the case of GeoJSON, and the default, unless the client explicitly requests crs=EPSG:3857
- What is hte original CRS for a TileMatrixSet if the local definition uses a different CRS defining the exact same grid (https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/55)

**Comment by joanma747** [comment]
The first bullet was fixed in #103 The second bullet will be fixed in when ([2D-Tile-Matrix-Set#55](https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/55)) is addressed.
