### ISSUE TITLE
verify consistency of the OpenAPI documents and the spec.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-tiles#76]
said!

**Comment by chris-little** [comment]
Very!

**Comment by jerstlouis** [comment]
Suggesting that we tackle the OpenAPI definitions at our next meeting, re-organizing them as `responses/`, `schemas/` and `parameters/`, and possibly referencing building blocks from common (for now we can copy them in the sub-folder until common is itself synchronized with Coverages) with up to date).

This is the organization used in all other OGC API specifications: [Features](https://github.com/opengeospatial/ogcapi-features/tree/master/core/openapi), [Common](https://github.com/opengeospatial/ogcapi-common/tree/master/collections/openapi), [Coverages](https://github.com/opengeospatial/ogcapi-coverages/tree/master/standard/openapi), [EDR](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/standard/openapi), [Processes](https://github.com/opengeospatial/ogcapi-processes/tree/master/core/openapi).

We should also review and synchronize with the API definitions of implementations such as [ours](https://maps.ecere.com/ogcapi/api).

**Comment by jerstlouis** [comment]
The API is now re-organized into easily re-usable building blocks, and can even be used directly by simply changing the example server if the dynamic `/api/*` end-points to list available resources (collections, tileMatrixSets, styles) are implemented.

See the latest [OpenAPI definition](https://github.com/opengeospatial/ogcapi-tiles/tree/master/openapi) with [SwaggerUI](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/opengeospatial/ogcapi-tiles/master/openapi/ogcapi-tiles-1.yaml).
