### ISSUE TITLE
URL paths of coverage tiles and vector tiles

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ogcapi-tiles#80]
It's been discussed that the URL path for map tiles of a collection should be `.../{collectionId}[/styles/{styleId}]/map/tiles` and that the URL path for data tiles of a collection should be `.../{collectionId}/tiles`.  In the case of coverage collections these data tiles would be coverage tiles (dataType="coverage"), and in the case of vector collections these data tiles would be vector tiles (dataType="vector").

However, a concern has been expressed that that it may be possible for a collection to have both vector and coverage features, and that therefore a single `.../{collectionId}/tiles` may be insufficient.  @jerstlouis has proposed that perhaps the URL path should be `.../{collectionId}/coverage/tiles` for coverage tiles.

I'm okay with going either way on this, but only if we go completely one way or the other.  I dislike the inconsistency of vector data tiles being at `.../{collectionId}/tiles` and coverage data tiles being at `.../{collectionId}/coverage/tiles`.  It should be either:

1. The URL path for data tiles of a collection is `.../{collectionId}/tiles`, and these tiles must be declared as either dataType="vector" or dataType="coverage".

or

2. The URL path for data tiles of a collection is `.../{collectionId}/items/tiles` (dataType="vector") and/or `.../{collectionId}/coverage/tiles` (dataType="coverage").

If we go with number 2, I don't know where that leaves us with respect to multi-collection data tiles, the URL path of which I believe is currently `{datasetLandingPage}/tiles`.

**Comment by cportele** [comment]
@pomakis - Option 2 is not an option. All sub-resources of `items` are the items in the collection (e.g., the features or records), not a Tilesets resource. 

To me `.../{collectionId}/tiles` is the appropriate path for the tilesets of a collection.

**Comment by pomakis** [comment]
Hmmm, true, `.../{collectionId}/items/tiles` would clash with `.../{collectionId}/items/{featureId}`.  Argh.

**Comment by jerstlouis** [comment]
@pomakis I agree with Clemens on `/items/tiles` not being an option`, but for Coverages we defined the path to be `/coverage/tiles`, and I believe we agreed to let the Coverages specifications to decide in this case (like Map defines the Map Tiles conformance class).

https://github.com/opengeospatial/ogcapi-coverages/blob/master/standard/requirements/coverage-tiles/REQ_cov-tiles-definition.adoc

So unfortunately I think we need to accept the discrepancy. But the idea is that the `tileset-*` relation type is what Tiles would specify. In our server, if the collection is only available as a coverage, we also respond with coverage tiles at `/tiles` for these.

**Comment by jerstlouis** [comment]
>  it may be possible for a collection to have both vector and coverage features

To clarify, those are the same "features" which could be accessed as both vector features and as a coverage.
A point cloud or dense sensor data are perfect examples, elevation grid/contours might be another.

**Comment by joanma747** [comment]
Can we accept the discrepancy and close this issue?

**Comment by pomakis** [comment]
So which way is it going?  Or is it left undefined until "OGC API - Coverages" decides?  Do they have an issue open to decide this?

**Comment by jerstlouis** [comment]
@pomakis It is already decided in Coverages:

https://github.com/opengeospatial/ogcapi-coverages/blob/master/standard/requirements/coverage-tiles/REQ_cov-tiles-definition.adoc

If it's moved to `/tiles` instead of `/coverage/tiles` then we lose the ability to have separate tilesets lists for coverages and vector tiles of the same collection, so how could that be solved?

**Comment by pomakis** [comment]
Okay, it looks like a done deal then.  Therefore, I don't mind if this issue gets closed.  I'll update CubeWerx's implementation.
