### ISSUE TITLE
Add an annex about TileJSON?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-tiles#88]
The core conformance class introduction suggests the existance of a tileJSON annex as an alternative to the tileset metadata as defined in 2D-TMS. I believe that at some point in time we had something but is not included in the spec. Do we really need it?

**Comment by joanma747** [comment]
the text "See Annex TBD for more details about this format." has been removed from the core conformance class intro for consistency with the absence of the annex. It cna be reintroduced if necessary

**Comment by jerstlouis** [comment]
@joanma747 I don't think we need that annex. TileJSON is specified by Mapbox and they can worry about better specifying anything it's currently missing. We were using an unreleased version 3 with some of our own tweaks in the past, so better to avoid including any of this.

For things that are already well specified, people can directly use whichever version is already released.

This dates from before we had a proper TileSet metadata specification listing vector layers, attributes/properties etc.

**Comment by joanma747** [comment]
In the last telecon we decided to skip this for reasons specified by @jerstlouis
