### ISSUE TITLE
Issues in current conformance overview, Abstract Test 6

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-tiles#90]
(In Clause 2 - Conformance)
"Core": no path is prescribed for this conformance class so no fixed path resource exists for this. The only requirement is that a URL template could be specified where 3 different variables correspond to tile matrix, tile row and tile column.

"TileSet": The resource path is wrong. Normally it is`…​/tiles/{tileMatrixSet}`, `…​/tiles/{tileMatrixSet}/{tileMatrix}` does not return anything.
However, again the path is not fixed yet for this conformance class, only the content must conform to TileSet Metadata standard.

"TileSets List": The resource path is also wrong. Normally it is`…​/tiles`. However again the path is not fixed, only the content must be a list of TileSets.

"DataSet TileSets": I think it would be easier to simply state that `/tiles` at the root of the API provides a TileSets List as defined in the other conformance classes.
"GeoData TileSets": I think it would be easier to simply state that `/collections/{collectionId}/tiles` for the collections provides a TileSets List as defined in the other conformance classes.

NOTE: The path to individual tiles might actually not be fixed at all. Only Recommendation 1 A says something about this:

> A tiles implementation should consider to use the tiles URI template variables in the following common order and form: {tileMatrix}/{tileRow}/{tileCol}

Abstract Test 6 may therefore be wrong, it should use a URL template rather than issue a GET to a fixed path:

> Issue an HTTP GET request to the URL with pattern /tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.

In fact the _Core_ conformance might be difficult to test by itself, since the URL template is only provided by the _TileSet_ conformance class.

To also support testing the Core, Tileset and Tilesets List conformance classes by themselves, the OGC API - Tiles CITE test would need to be able to accept different types of URLs as well of a selection of what type of URL it is:
- An OGC API dataset root URL
- An OGC API - Tiles List of tilesets
- An OGC API - Tiles TileSet
- A tiles template URL

**Comment by joanma747** [comment]
CITE will not be able to test the core class except if there is a way to provide to the test suite the template URL (that contains the endpoint for the tiles) and a range of valid values for the parameters in the template to execute the test.
we recommend to start by the second conformance class and them build a user interface (with a form asking for URI templates ...) for the core.

The other comment has been applied in the section 2 conformance.

**Comment by joanma747** [comment]
A note is added in the ATS to remember about this way of testing the core.
